### PR TITLE
Added fix to a troubleshooting problem and changed the command to generate tokens

### PR DESCRIPTION
**Pull request by kishansag**
1.

The command that was shown earlier would end up in an error
```
$ ./bin/auth-cli generate login -H localhost:8089 --help
Generate a set of Tokens for different Auth levels. NOT FOR PRODUCTION. Only available if server is running in dev mode

Usage:
  auth-cli generate [command]

Available Commands:
  token       

Global Flags:
      --dump               Dump HTTP request and response.
      --format string      Format used to create auth header or query from key (default "Bearer %s")
  -H, --host string        API hostname (default "openshift.io")
      --key string         API key used for authentication
  -s, --scheme string      Set the requests scheme
  -t, --timeout duration   Set the request timeout (default 20s)

Use "auth-cli generate [command] --help" for more information about a command.
```
2.
fix for
```
[ERROR]	Failed to set references: Unable to update checked out version (Skip to cleanup)
make: *** [vendor] Error 1
```

### CODE REVIEW

**Comment by kbsingh** [comment]
[test]

**Comment by alexeykazakov** [comment]
[test]

**Comment by alexeykazakov** [comment]
[test]

**Comment by alexeykazakov** [comment]
[test]

**Pull request merged**
