### PR TITLE
Support to add inital admin in Register Resource API

### LINKED ISSUE #693: Add admin during resource registration
Should we modify the resource registration API to also include the identityID of the user who would have the scope to manage roles for the specific resource? The user would be assigned the `admin` ( or something similar ) for that resource at the time of resource registration.

Without this, there's no way to assign a role to an arbitrary user to a resource, after resource registration.

### PR DESCRIPTION
**Pull request by sbose78**
"Let's add a new nullable column to the RESOURCE_TYPE table, called DEFAULT_ROLE_ID, with a foreign key constraint to the ROLE.ROLE_ID column. Then, when registering a new resource, the resource service will look for a value in this column, and if found, assign the specified role to the creating user for the new resource. This change also requires that we pass in the current user's IDENTITY_ID value as a parameter to the resource_service.Register() function."

fixes #693

### CODE REVIEW

**Comment by fabric8cd** [comment]
@sbose78 snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-694-1`

**Comment by fabric8cd** [comment]
@sbose78 snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-694-2`

**Comment by fabric8cd** [comment]
@sbose78 snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-694-3`

**Comment by fabric8cd** [comment]
@sbose78 snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-694-4`

**Comment by fabric8cd** [comment]
@sbose78 snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-694-5`

**Comment by fabric8cd** [comment]
@sbose78 snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-694-6`

**Comment by alien-ike** [comment]
### Ike Plugins (pr-sanitizer)

Thank you @sbose78 for this contribution!



This pull request doesn't comply with the conventions given by the `pr-sanitizer` plugin. The following items are necessary to fix:

#### Semantic title
The PR title `Support to add inital admin in Register Resource API` does not conform with the [semantic message](https://seesparkbox.com/foundry/semantic_commit_messages) style. The semantic message makes your changelog and git history clean. Please, edit the PR by prefixing it with one of the type prefixes that are valid for your repository: `chore`, `docs`, `feat`, `fix`, `refactor`, `style`, `test`.

For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_pr_sanitizer_plugin). You can find there how to configure the plugin.

**Comment by sbose78** [comment]
Yeah, just `identityID` sounds better. Has been bothering me a bit as well.

**Comment by fabric8cd** [comment]
@sbose78 snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-694-7`

**Pull request merged**
