### PR TITLE
Use test with no coverage by default

### PR DESCRIPTION
**Pull request by alexeykazakov**
We can now just run `make test-*` to run test with no coverage and `make test-*-with-coverage` to run tests with coverage.

1. `make test-unit, test-integration, and test-remote` renamed to `test-unit-with-coverage, test-integration-with-coverage, test-remote-with-coverage`

2. `make test-unit-no-coverage, test-integration-no-coverage, and test-remote-no-coverage` renamed to `test-unit, test-integration, test-remote`

3. `make test-all` now runs test with no coverage.

4. Some clean up.

### CODE REVIEW

**Comment by alexeykazakov** [comment]
[test]

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-220-1`

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-220-2`

**Comment by sbose78** [comment]
My only concern is that now the `make` target names are not consistent with the other golang projects :)

**Comment by alexeykazakov** [comment]
Yeah... that concerns me too a bit... but I forgot when I used test with coverage target :)

**Pull request merged**
