### PR TITLE
Remove auth route from OS template

### PR DESCRIPTION
**Pull request by alexeykazakov**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-380-1`

**Comment by alexeykazakov** [comment]
This route is actually is used by WIT - https://github.com/fabric8-services/fabric8-wit/blob/master/configuration/configuration.go#L822
It's used by WIT->Auth proxy. The full URL is not working in proxy for some reason. This is why we use "auth" route in WIT.

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @alexeykazakov for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by alexeykazakov** [comment]
It turned out that we don't need a route to reach auth internally. http://auth still will be availability internally and will point to the auth service. So, we can remove the route.

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-380-2`

**Comment by sbose78** [comment]
Nice - just saw the discussion too :)

**Pull request merged**
