### PR TITLE
Check local DB first when retrieving external tokens

### PR DESCRIPTION
**Pull request by alexeykazakov**
When retrieving a GitHub or OS token check the local DB first. If there is nothing then check Keycloak. If Keycloak has a token then save it in the local DB and return.

Also improved Delete token API. Now it deletes all the tokens from the local DB for the given provider ID and identity. It should not normally happen (multiple tokens) but technically it's possible if there are a few linking requests in the same time.
We also now remove the link from Keycloak when deleting tokens.

Fixes https://github.com/fabric8-services/fabric8-auth/issues/156

### CODE REVIEW

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-155-1`

**Comment by alexeykazakov** [comment]
> Sometime it also gave 301 Moved Permanently

Hmm.. This is weird. You should not get 301. Could you please try to debug it and see what causes such 301 responses?

> Manually entered few more external_tokens (two with same access token one with different) in the database. It deletes all the tokens. Is this the expected behaviour?

You mean a few tokens for the same Identity ID and Token Provider? If so then yes, this is expected. It could theoretically happen (multiple tokens) if a few concurrent linking requests (for the same user) happened, so we should delete all the tokens.

**Comment by alexeykazakov** [comment]
[test]

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-155-3`

**Comment by alexeykazakov** [comment]
[test]

**Comment by alexeykazakov** [comment]
We will need to add `ctx.ResponseData.Header().Set("Access-Control-Expose-Headers", "WWW-Authenticate")` to the response. See https://github.com/fabric8-services/fabric8-auth/pull/182/

**Comment by kishansagathiya** [comment]
@alexeykazakov 
Ran this https://github.com/fabric8-services/fabric8-auth/pull/155#pullrequestreview-73144141 again. No more 301. Seems fine to me.
- Deletes all the external_tokens with the respective Identity ID and Token Provider
- Checks the db, if no external token, prints "Unable to delete Identity Provider link from Keycloak. That's OK if the link doesn't exist."

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-155-5`

**Comment by alexeykazakov** [comment]
@kishansagathiya thanks for the update.

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-155-6`

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-155-7`

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-155-11`

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-155-12`

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-155-13`

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-155-14`

**Comment by sbose78** [comment]
So this in *in* - Good :)

**Pull request merged**
