### PR TITLE
ignore error when audit log creation failed

### PR DESCRIPTION
**Pull request by xcoulon**
* Please describe what your change is about.
* What issues does it solve? (Use [autoreferencing for this](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests))
* If you are still working on the change please prefix the pull request title with "WIP"

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @xcoulon for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/fabric8-services/fabric8-auth/blob/5fae61af1bd503b5e851f42b9a72607db0e4a2e3/.ike-prow/test-keeper.yaml).

**Comment by alexeykazakov** [comment]
[test]

**Pull request merged**
