### PR TITLE
Validate all incoming tokens

### PR DESCRIPTION
**Pull request by alexeykazakov**
Regardless of security declaration in goa design definition we should validate all incoming tokens.
For example if we do not require Authorization header in /api/users/:ID we still check the token in case the request is coming from a Service Account. We should validate such tokens anyway.

This PR modifies our logging middleware. Now we not only add all the tokens in the context but also validate them. If there is Authorization header with a bearer token then we will validate it. If token is not valid then 401 will be returned.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-306-1`

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-306-2`

**Comment by sbose78** [comment]
And also tried out incorrect token!
`{"errors":[{"code":"unauthorized_error","detail":"There is no public key with such ID: zD-57oBFIMUZsAWqUnIsVu_x71VIjd1irGkGUOiTsL8","status":"401","title":"Unauthorized error"}]}`

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-306-3`

**Comment by aslakknutsen** [comment]
> And also tried out incorrect token!

That was kinda the important part.. ;)

**Comment by sbose78** [comment]
I was more worried about breaking things, initially. :D

**Pull request merged**
