### PR TITLE
Create dev tokens in WIT

### PR DESCRIPTION
**Pull request by sbose78**
Previously when we generated test tokens, we used to create the identities in WIT as well - that code went away when we started supporting token generation inside Auth service, causing the wit+auth dev workflow to be broken. This PR puts that code back.

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @sbose78 for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/fabric8-services/fabric8-auth/8c4054e314651b5b9f8bf3a63da8475ec0fe01fe/test-keeper.yml).

**Comment by alexeykazakov** [comment]
@sbose78 the code doesn't compile after rebasing :)

**Comment by fabric8cd** [comment]
@sbose78 snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-488-3`

**Pull request merged**
