### PR TITLE
get a working release pipeline for fabric8 platform

### PR DESCRIPTION
**Pull request by alexeykazakov**
Fixes https://github.com/fabric8-services/fabric8-auth/issues/86

### CODE REVIEW

**Comment by alexeykazakov** [comment]
Merging so we don't block fabric8 builds

**Comment by rawlingsj** [comment]
awesome! thanks @alexeykazakov

**Comment by rawlingsj** [comment]
BTW I just added the webhooks to this repo to trigger CI and CD builds

**Comment by alexeykazakov** [comment]
@rawlingsj oh thanks. I was about to ask you for that ;)

**Pull request merged**
