### PR TITLE
Init tenant when /user is called

### PR DESCRIPTION
**Pull request by alexeykazakov**
UI is now using Auth to call /user so we need to init tenant service in Auth now instead of relaying on WIT /user

### CODE REVIEW

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-188-1`

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-188-2`

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-188-3`

**Comment by alexeykazakov** [comment]
[test]

**Pull request merged**
