### PR TITLE
Added `type` to cluster data

### PR DESCRIPTION
**Pull request by kishansagathiya**
fabric8-cluster service has added one more field `type` in cluster data
Since `/clusters` endpoint of auth just proxies to fabric8-cluster,
fabric8-auth should add that field as well

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @kishansagathiya for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/fabric8-services/fabric8-auth/blob/fd42a857918020ee4b2b1a6c8d731020d4425996/.ike-prow/test-keeper.yaml).

**Comment by alexeykazakov** [comment]
Auth proxies /clusters requests to Cluster service. So, this PR is purely about swagger docs in Auth service. Actual responses from Auth already include Type because cluster service supports this.
Auth acts as a dumb proxy here. So @kishansagathiya you don't have to wait for this PR to be merged to start using Type :) It's already there.

**Comment by alexeykazakov** [comment]
Closing as outdated.

**Pull request closed without merging**
