### PR TITLE
Upgrade to go v11.1 for test-coverage CI

### PR DESCRIPTION
**Pull request by alexeykazakov**
Fixes https://github.com/fabric8-services/fabric8-auth/issues/708

### CODE REVIEW

**Comment by alexeykazakov** [comment]
Coverage build fails because gofmt was changed in v.1.11.
The coverage build uses go v1.11.1 but the main CI job uses go from centos image which is 1.9 (as far as I remember).
I think we have to skip gofmt check for the coverage build and keep it for the main build only.

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @alexeykazakov for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/fabric8-services/fabric8-auth/blob/43638339927115d12380cb65dc17cd38ca584ca2/.ike-prow/test-keeper.yaml).

**Comment by alexeykazakov** [comment]
I'm switched all builds to go v.11.1 from the site in that PR and fixed formatting. Let's see if it's acceptable. If not then we can just skip formatting check when run tests with coverage.

**Comment by sbose78** [comment]
> I think we have to skip gofmt check for the coverage build and keep it for the main build only.
Agreed, coverage build shouldn't really have an business with gofmt checks.

I'm fine with this change - upgrading to go 11.1 sounds good to me. Good find @sbryzak !

**Pull request merged**
