### PR TITLE
add .golangci.yml

### PR DESCRIPTION
**Pull request by jirfag**
As was suggested in https://github.com/golangci/golangci/issues/18, we've supported custom build commands in `.golangci.yml`. Now this repo can be successfully analyzed by https://golangci.com

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @jirfag for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/fabric8-services/fabric8-auth/blob/0097723d95fbf59a573046f63d010ef3d7bac48b/.ike-prow/test-keeper.yaml).

**Comment by xcoulon** [comment]
thanks a lot for the fix @jirfag ! We're going to give it a try!

**Comment by alexeykazakov** [comment]
[test]

**Comment by alexeykazakov** [comment]
I see... 
We disabled this webhook sometime ago. We re-enabled it again but only after you submitted this PR. So I tried to trigger it for that pr by temporarily adding “comment” event. 
So, we ether should push something to your branch or create a new PR :)

**Comment by jirfag** [comment]
ok, got it.
I've force-pushed, [analysis](https://golangci.com/r/github.com/fabric8-services/fabric8-auth/pulls/716) was performed successfully :)

**Comment by alexeykazakov** [comment]
[test]

**Comment by jirfag** [comment]
thank you for the fast checking and approval!

**Comment by jirfag** [comment]
also now [repo report](https://golangci.com/r/github.com/fabric8-services/fabric8-auth) works ok

**Comment by xcoulon** [comment]
that's awesome, @jirfag 🎉thanks a lot!

**Pull request merged**
