### PR TITLE
Return 200 with payload instead of 303 when initiate account linking

### PR DESCRIPTION
**Pull request by alexeykazakov**
1. `POST token/link` with a payload (token, for, redirect) is replaced by `GET token/link?for=<>&redirect=<>` and Authorization header.

2. `token/link` now returns 200 with the following payload:
```
{"redirect_location":"<URL>"}
```
instead of 303 with `Location` header.

3. Some cleanup in tests

This PR can be tested via https://github.com/alexeykazakov/linker (updated to the new API)

Required by https://github.com/fabric8-services/fabric8-auth/issues/157
Part of https://github.com/fabric8-services/fabric8-auth/issues/21

### CODE REVIEW

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-211-1`

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-211-2`

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-211-3`

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-211-4`

**Comment by sbose78** [comment]
Note:
https://github.com/fabric8-services/fabric8-auth/pull/211/files#diff-6d42942038923aa03684ba83f0ab86fd 
is the only change relevant to the supporting of 200 OK. The rest is cleanup.

**Pull request merged**
