### PR TITLE
fix port

### PR DESCRIPTION
**Pull request by sbose78**
.. for test env setup

### CODE REVIEW

**Comment by sbose78** [comment]
[test]

**Comment by fabric8cd** [comment]
@sbose78 snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-11-1`

**Comment by sbose78** [comment]
@alexeykazakov yeah.. i know. I was trying to see if we can have the same port but use a different database inside it ( similar to the way its done in `init-tenant` where a database named `tenant` is used in the same db server as wit )

**Comment by sbose78** [comment]
[test]

**Comment by sbose78** [comment]
trying this out so that SD can proceed with setup of pipelines - was getting this error   

```
--- FAIL: TestMigrations (0.00s) panic: dial tcp 172.17.0.3:5433: getsockopt: connection refused [recovered] panic: dial tcp 172.17.0.3:5433: getsockopt: connection refused
```

but looks like there's the issue of entitlements' test failing..

**Comment by hectorj2f** [comment]
@sbose78 connection refused means that there is a problem to talk to the db, no ?

**Comment by sbose78** [comment]
@hectorj2f : could be an issue with the db being setup on a different port for tests: https://github.com/fabric8-services/fabric8-wit/blob/master/.make/docker-compose.integration-test.yaml

**Comment by alexeykazakov** [comment]
[test]

**Comment by alexeykazakov** [comment]
The entitlement test failed because there were too many resources for the test user in our test realm. I suspect there are some test outside of wit and auth services that create a lot of spaces/resources for the test user and don't bother to remove the spaces properly. As a result the request to obtain an RPT for all resources fails (too big response which killed by OS).
I now cleaned the resources so test are passing again (in both auth and wit).
@sbose78 we need to remove all tests that obtain all the resources available to the user as part of your work on stopping obtaining all the resources.

**Comment by alexeykazakov** [comment]
@sbose78 well, this PR actually doesn't specify a new DB name. It's still using the same "postgres" name. But even if we change the DB name the "make dev" command will fail if there is already a postgres container running created by make dev for fabric8-wit.

I tried to make the make_postgres_integration_test_1 container available via 5433 but it still fails:  https://github.com/fabric8-services/fabric8-auth/pull/12/files

@hectorj2f if I apply https://github.com/fabric8-services/fabric8-auth/pull/12/files then the DB is available via 0.0.0.0:5433 but not via 172.17.0.3:5433.
But even if I set AUTH_POSTGRES_HOST to 0.0.0.0 from 172.17.0.3 then 0.0.0.0:5433 is still unavailable from the auth container. But I can connect to the DB from my host (0.0.0.0:5433).

Any idea how to fix it?

**Comment by sbose78** [comment]
I was trying to use db auth + port 5432 here in this commit and then removed it because our tests failed to find the `auth` database. 

https://github.com/fabric8-services/fabric8-auth/pull/11/commits/1ab8c2f26082dae8295b1a2243893b9c6db24d2c

**Comment by sbose78** [comment]
> @sbose78 we need to remove all tests that obtain all the resources available to the user as part of your work on stopping obtaining all the resources.

Okay, will do this.

**Comment by fabric8cd** [comment]
@sbose78 snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-11-2`

**Comment by alexeykazakov** [comment]
[test]

**Pull request merged**
