### PR TITLE
Fixing tests for /user

### PR DESCRIPTION
**Pull request by kishansagathiya**
Tests weren't running since TestRunUserREST() was defined as a method of TestUserREST. Two failing tests are yet to be fixed
```
=== RUN   TestCurrentAuthorizedNotModifiedUsingIfModifiedSinceHeader
--- FAIL: TestCurrentAuthorizedNotModifiedUsingIfModifiedSinceHeader (0.00s)
	user_testing.go:236: invalid response status code: got 200, expected 304
=== RUN   TestCurrentAuthorizedNotModifiedUsingIfNoneMatchHeader
--- FAIL: TestCurrentAuthorizedNotModifiedUsingIfNoneMatchHeader (0.00s)
	user_testing.go:236: invalid response status code: got 200, expected 304
```
#232

### CODE REVIEW

**Comment by sbose78** [comment]
@kishansagathiya , looks good - Can you fix the tests and get this PR ?

**Comment by sbose78** [comment]
@kishansagathiya , looks good - Can you fix the tests and get this PR in ?

**Comment by kishansagathiya** [comment]
Thanks a lot to @xcoulon for the help

**Comment by fabric8cd** [comment]
@kishansagathiya snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-235-2`

**Pull request merged**
