### PR TITLE
remove go-vcr implementation

### PR DESCRIPTION
**Pull request by dipak-pawar**
This Removes all code which is not using in any of the tests as we have swiched for gock from go-vcr

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @dipak-pawar for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/fabric8-services/fabric8-auth/blob/e75fc6473709de3ed43646c5fc5aed60c73d2552/.ike-prow/test-keeper.yaml).

**Comment by dipak-pawar** [comment]
@xcoulon Can you take care of ike?

**Comment by alien-ike** [comment]
Hey @dipak-pawar! It seems you tried to trigger `/ok-without-tests` command, but this will not have any effect due to insufficient permission. You have to be admin or requested reviewer or pull request approver, but not pull request creator for this command to take an effect.

**Comment by dipak-pawar** [comment]
thank you @xcoulon

**Pull request merged**
