### PR TITLE
chore(#485): remove ike-prow-plugin configuration file test-keeper.yml

### PR DESCRIPTION
**Pull request by dipak-pawar**
Fixes: #485 

Depends on #https://github.com/arquillian/ike-prow-plugins/pull/144

### CODE REVIEW

**Comment by alexeykazakov** [comment]
[test]

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @dipak-pawar for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by MatousJobanek** [comment]
The referenced issue has been already merged and deployed to the new Ike plugins instance, so you can merge this PR

**Comment by alexeykazakov** [comment]
[test]

**Pull request merged**
