### PR TITLE
Clean up space authorization code

### PR DESCRIPTION
**Pull request by alexeykazakov**
We do not use RPT tokens to authorize a user in spaces anymore. So, this PR removes code that checkes if the access token is an RPT token otherwise calls Keycloak to check entitlement. We should just call Keycloak to obtain an entitlement.

Part of https://github.com/fabric8-services/fabric8-auth/issues/65

### CODE REVIEW

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-106-1`

**Comment by alexeykazakov** [comment]
[test]

**Comment by alexeykazakov** [comment]
> nostalgic that the RPT code is gone

Yeah.. have to throw away our efforts to use KC RPT. But no worries, new authZ is coming. New and shiny :)

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-106-2`

**Pull request merged**
