### PR TITLE
Override email privacy using notification service token

### PR DESCRIPTION
**Pull request by sbose78**
Partially fixes https://github.com/fabric8-services/fabric8-notification/issues/52

**TODO**

- [x] Add tests
- [x] Update `GET /api/users/<ID>` API

**How to test**

1. Get service account token: 
```
curl --request POST   -d "grant_type=client_credentials&client_id=4c34f6d4-f00b-487b-9a1f-e7d1adba6866&client_secret=secret"  --url http://localhost:8089/api/token  
```

2. Pass token in the request 
```
curl --header "authorization: bearer $token" http://localhost:8089/api/users/7587730b-a4c0-4023-aa3a-dde91a3f5fd5
```

### CODE REVIEW

**Comment by fabric8cd** [comment]
@sbose78 snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-252-1`

**Comment by fabric8cd** [comment]
@sbose78 snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-252-2`

**Comment by fabric8cd** [comment]
@sbose78 snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-252-3`

**Comment by sbose78** [comment]
Excellent, thank you very much @alexeykazakov :D

**Pull request merged**
