### PR TITLE
Remove unused Keycloak OSO and GitHub linking API

### PR DESCRIPTION
**Pull request by alexeykazakov**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-321-1`

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-321-2`

**Comment by sbose78** [comment]
Will test out login and link workflows manually before merging this. The code changes/removals look fine to me.

**Comment by fabric8cd** [comment]
@alexeykazakov snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-321-3`

**Pull request merged**
