### PR TITLE
Add constraint for allowed user search query string

### PR DESCRIPTION
**Pull request by sbose78**
When user is searched using the API:
this change will ensure that the search string contains at least 1 character in the set A-Z,a-z,0-9
`https://auth.openshift.io/api/search/users?q=@.`  not allowed.
`https://auth.openshift.io/api/search/users?q=bose@` allowed.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@sbose78 snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-217-1`

**Comment by alexeykazakov** [comment]
What if username is just "a"? or "ab"? Unlikely but still technical possible. We should make sure we don't break anything on UI side for super short usernames.

**Comment by sbose78** [comment]
I've update my PR to now check for the A-Z,a-z,0-9 in the search query string + tests. 
It is ready for review!

**Comment by fabric8cd** [comment]
@sbose78 snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-217-2`

**Comment by fabric8cd** [comment]
@sbose78 snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-217-3`

**Pull request merged**
