### PR TITLE
Fix intermittent failure of role management service test

### LINKED ISSUE #463: Fix intermittent failure in RunRoleManagementServiceBlackboxTest
We are still experiencing failures of this test on some occasions:

```
--- FAIL: TestRunRoleManagementServiceBlackboxTest (0.63s)
    --- FAIL: TestRunRoleManagementServiceBlackboxTest/TestGetRolesByResourceTypeOK (0.02s)
        assertions.go:247: 
                          
    Error Trace:    role_management_service_blackbox_test.go:174
            
                    
            role_management_service_blackbox_test.go:119
            
    Error:          Received unexpected error:
            
                    role with id '67f9e88c-39ee-42e0-9b3c-cf706f8fd1dc' not found
            
    Test:           TestRunRoleManagementServiceBlackboxTest/TestGetRolesByResourceTypeOK
```

### PR DESCRIPTION
**Pull request by sbryzak**
Fixes #463

This PR adds a `deleted_at IS NULL` condition for both the `role` and `resource_type` tables in the SQL for `RoleRepository.FindRolesByResourceType()`.  This should fix the error we sometimes see in the test.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@sbryzak snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-464-1`

**Comment by alexeykazakov** [comment]
[test]

**Comment by alexeykazakov** [comment]
[test]

**Comment by fabric8cd** [comment]
@sbryzak snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-464-2`

**Comment by sbryzak** [comment]
[test]

**Comment by sbryzak** [comment]
[test]

**Comment by sbose78** [comment]
[test] heard its back.

**Pull request merged**
