### PR TITLE
Add missing deleted_at conditions to raw queries

### LINKED ISSUE #466: Add deleted_at clause to SQL where required
I've found two places where we don't have a deleted_at condition for raw queries:

1. identities.deleted_at in Search() query:

[https://github.com/fabric8-services/fabric8-auth/blob/master/account/identity.go#L374](https://github.com/fabric8-services/fabric8-auth/blob/master/account/identity.go#L374)

2. identity_role.deleted_at (and more) in FindPermissions() query:

[https://github.com/fabric8-services/fabric8-auth/blob/master/authorization/role/repository/identity_role.go#L183](https://github.com/fabric8-services/fabric8-auth/blob/master/authorization/role/repository/identity_role.go#L183)

### PR DESCRIPTION
**Pull request by sbryzak**
This PR adds `deleted_at` conditions to both the identity search, and identity_role find permissions queries which both use raw SQL.

Fixes #466

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @sbryzak for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/fabric8-services/fabric8-auth/a87cc7dae610a89dfcc5423e243ecfb7ab3864cd/test-keeper.yml).

**Comment by fabric8cd** [comment]
@sbryzak snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-467-1`

**Comment by fabric8cd** [comment]
@sbryzak snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-467-2`

**Comment by fabric8cd** [comment]
@sbryzak snapshot fabric8-auth image is available for testing.  `docker pull docker.io/fabric8/fabric8-auth:SNAPSHOT-PR-467-3`

**Pull request merged**
